version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: 24h_billiard_frontend
    restart: unless-stopped
    ports:
      - "3001:3000"
      
    networks:
      - 24h_network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: 24h_billiard_backend
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/backend
    working_dir: /var/www/backend
    ports:
      - "8001:8000"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://tinhtien.24hbilliardscoffee.com
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=24h_billiard
      - DB_USERNAME=backend_usr
      - DB_PASSWORD=Lrv@2025
    depends_on:
      - mysql

    networks:
        - 24h_network
  mysql:
    image: mysql:8.0
    container_name: 24h_billiard_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: RootLrv@2025
      MYSQL_DATABASE: 24h_billiard
      MYSQL_USER: backend_usr
      MYSQL_PASSWORD: Lrv@2025
    ports:
      - "3308:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d

    networks:
      - 24h_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: 24h_billiard_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: backend_usr
      PMA_PASSWORD: Lrv@2025
    ports:
      - "8081:80"
    depends_on:
      - mysql

    networks:
      - 24h_network

  nginx:
    image: nginx:latest
    container_name: 24h_billiard_nginx
    restart: unless-stopped
    ports:
      - "81:80"
      - "444:443"
    volumes:
      - ./frontend:/var/www/frontend
      - ./backend:/var/www/backend
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - mysql
      - backend
      - frontend

    networks:
      - 24h_network

volumes:
  mysql_data:

networks:
  24h_network:
    driver: bridge
