server {
    listen 80;
    server_name tinhtien.24hbilliardscoffee.com;

    root /var/www/html/bida-24h/backend/public;  # Laravel backend

    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass   php:9000;   # cần container php-fpm
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location /frontend {
        root /var/www/html/bida-24h;
        index index.html;
    }
}
